/*
 * DaVinci interrupt controller definitions
 *
 *  Copyright (C) 2006 Texas Instruments.
 *
 *  This program is free software; you can redistribute  it and/or modify it
 *  under  the terms of  the GNU General  Public License as published by the
 *  Free Software Foundation;  either version 2 of the  License, or (at your
 *  option) any later version.
 *
 *  THIS  SOFTWARE  IS PROVIDED   ``AS  IS'' AND   ANY  EXPRESS OR IMPLIED
 *  WARRANTIES,   INCLUDING, BUT NOT  LIMITED  TO, THE IMPLIED WARRANTIES OF
 *  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN
 *  NO  EVENT  SHALL   THE AUTHOR  BE    LIABLE FOR ANY   DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 *  NOT LIMITED   TO, PROCUREMENT OF  SUBSTITUTE GOODS  OR SERVICES; LOSS OF
 *  USE, DATA,  OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 *  ANY THEORY OF LIABILITY, WHETHER IN  CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 *  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *  You should have received a copy of the  GNU General Public License along
 *  with this program; if not, write  to the Free Software Foundation, Inc.,
 *  675 Mass Ave, Cambridge, MA 02139, USA.
 *
 */
#ifndef __ASM_ARCH_IRQS_H
#define __ASM_ARCH_IRQS_H

#include <mach/chip.h>

//intc
#define		REG_IRQ_EN_LOW				(INTC_REG_BASE + 0x0000)
#define		REG_IRQ_EN_HIGH				(INTC_REG_BASE + 0x0004)
#define		REG_IRQ_IRQMASK_LOW			(INTC_REG_BASE + 0x0008)
#define		REG_IRQ_IRQMASK_HIGH		(INTC_REG_BASE + 0x000C)
#define		REG_IRQ_IRQFORCE_LOW		(INTC_REG_BASE + 0x0010)
#define		REG_IRQ_IRQFORCE_HIGH		(INTC_REG_BASE + 0x0014)
#define		REG_IRQ_RAWSTATUS_LOW		(INTC_REG_BASE + 0x0018)
#define		REG_IRQ_RAWSTATUS_HIGH		(INTC_REG_BASE + 0x001C)
#define		REG_IRQ_STATUS_LOW			(INTC_REG_BASE + 0x0020)
#define		REG_IRQ_STATUS_HIGH			(INTC_REG_BASE + 0x0024)
#define		REG_IRQ_MASKSTATUS_LOW		(INTC_REG_BASE + 0x0028)
#define		REG_IRQ_MASKSTATUS_HIGH		(INTC_REG_BASE + 0x002C)
#define		REG_IRQ_FINSTATUS_LOW		(INTC_REG_BASE + 0x0030)
#define		REG_IRQ_FINSTATUS_HIGH		(INTC_REG_BASE + 0x0034)
#define		REG_FIQ_EN_LOW				(INTC_REG_BASE + 0x02C0)
#define		REG_FIQ_EN_HIGH				(INTC_REG_BASE + 0x02C4)
#define		REG_FIQ_FIQMASK_LOW			(INTC_REG_BASE + 0x02C8)
#define		REG_FIQ_FIQMASK_HIGH		(INTC_REG_BASE + 0x02CC)
#define		REG_FIQ_FIQFORCE_LOW		(INTC_REG_BASE + 0x02D0)
#define		REG_FIQ_FIQFORCE_HIGH		(INTC_REG_BASE + 0x02D4)
#define		REG_FIQ_RAWSTATUS_LOW		(INTC_REG_BASE + 0x02D8)
#define		REG_FIQ_RAWSTATUS_HIGH		(INTC_REG_BASE + 0x02DC)
#define		REG_FIQ_STATUS_LOW			(INTC_REG_BASE + 0x02E0)
#define		REG_FIQ_STATUS_HIGH			(INTC_REG_BASE + 0x02E4)
#define		REG_FIQ_FINSTATUS_LOW		(INTC_REG_BASE + 0x02E8)
#define		REG_FIQ_FINSTATUS_HIGH		(INTC_REG_BASE + 0x02EC)

#define NR_IRQS	(NR_INTERNAL_IRQS+NR_EXTERNAL_IRQS)


#endif /* __ASM_ARCH_IRQS_H */
